# .github/workflows/**main.yml**
name: Django-app workflow

on: [push]

jobs:
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск actions checkout — готового скрипта 
    # для клонирования репозитория
    - uses: actions/checkout@v2
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта 
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        # Выбор версии Python
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и his плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py — 
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test

    # Сразу после них добавьте новую задачу: деплой приложения
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: abramow79/8ec6f623a216f147ea97e04350cfaf67c9375a58aa087a43b09153afc164033f:latest
          # ваш-логин-на-docker-hub/ваш-репозиторий-на-docker-hub:latest 
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAwu3J6QGTVVnIbkxAQfKJMfmRjB5iXyqYXnrHotLj+zNuxZ6v2AEs
8BosBI/NP+5kbJ0y446wX5xWy8gJrUzOSEwrAYxPOR8W0Xu2dvqgxIPvDqHtdy/QRinwCz
UlOvmuc5RSiaaL7ML3h2HH/7yyAHDnDH0VmGUWre4P+uNDuheF/hLf98hLxiUWl6pDtkL9
r5rN7xgWBzAVvRsuMDtxsoi29PZR9pevQhDBBen/5uv7vGEYASY+5VxQB0CeOH+FufW3rC
fEwHr7gtPkISYeGTwH9zdwPMpJq2VBaZU6zNdIQOlUC19hceXGwLHk48ihzaaox5UgG9YL
H9XCruU3PLWTq4tGq2Qshk/syZuxDTtxRAFpFpvtMa9v2hlE6sGDaJ+36Onk3PbA0O1IzZ
DACpgvCZUlp6JNtjn+c9r2htQBhBNWjFJzyIjpMmrZK3oLg39/bdGXIBoZsUkFao+viAhk
H9fd2rfA6QVaDuour00YO42Kog6IeNu9LS7Q+M17AAAFkEwnSd1MJ0ndAAAAB3NzaC1yc2
EAAAGBAMLtyekBk1VZyG5MQEHyiTH5kYweYl8qmF56x6LS4/szbsWer9gBLPAaLASPzT/u
ZGydMuOOsF+cVsvICa1MzkhMKwGMTzkfFtF7tnb6oMSD7w6h7Xcv0EYp8As1JTr5rnOUUo
mmi+zC94dhx/+8sgBw5wx9FZhlFq3uD/rjQ7oXhf4S3/fIS8YlFpeqQ7ZC/a+aze8YFgcw
Fb0bLjA7cbKItvT2UfaXr0IQwQXp/+br+7xhGAEmPuVcUAdAnjh/hbn1t6wnxMB6+4LT5C
EmHhk8B/c3cDzKSatlQWmVOszXSEDpVAtfYXHlxsCx5OPIoc2mqMeVIBvWCx/Vwq7lNzy1
k6uLRqtkLIZP7MmbsQ07cUQBaRab7TGvb9oZROrBg2ift+jp5Nz2wNDtSM2QwAqYLwmVJa
eiTbY5/nPa9obUAYQTVoxSc8iI6TJq2St6C4N/f23RlyAaGbFJBWqPr4gIZB/X3dq3wOkF
Wg7qLq9NGDuNiqIOiHjbvS0u0PjNewAAAAMBAAEAAAGALHjj3+0kGAzr1X5ACsuy0VwHAN
jNyLiHGscYVOWYbe9GDoAtzjI2dnECKehFA5j4AG+89H3Rb37Trpps2sTzKzt1dFz2limp
oxF+h5aWpz8Sg1weOVsHQXq/8U6mt9XPHz9vtUfyFIpGvvRoFMiQM9mOXSMMkkA99GCj9L
F0+jfzsgvMXVOtNf+wL9oAqMyP5EiFQ09Td0BZNVPGLerh/cGDPFAWUxQ4P/Jil17Tq3Ob
c1cTiu+W2e09tOnhLzKogdmPPDhYKP5ZW9Ywa6ep/SusTNAv4lvQE4T7AtEuSFhI+2LqFh
CFJYC1RtLSATqiqBipflrPrD8ByhETxaVABqM+uvUwJ+pSNOkbYpNLrOdOzCl1e6h104JO
sZNkujwEJn1nj1brtnBSdIQeYuQknO9TMGdJZcOMdYLHRQK9LBhj7O6AJn/Q9FcPsI+bLr
qMtjIf0NQL91gVso4MnROhK+pWUAMxm82pfE3+KEtiLfephgnLr7J2jrZOC3jnROQBAAAA
wQCvwAr7In+PN0VEnza6hEr2wy6EUL4qAgqv6aV4TNQaxO0bS3HCrBGXflylbI/aytdHvt
ZtbZleem1Bj8D7gNoedg5h8OnOQ6le9TxhWWP4RMmGmA1IEFUw+Ma0q7qeK+NDDvNOSuXY
OhCRfuQWkv784MSF2KQaeGUtuMlB7yhBQixH+qNUCSl3EgzEQ1lkZKhGrvrTaNCT/gwhEc
8yozkCilREFKa3pwOKVnvHyXTyV2T4hPc/NJ0Ai6VDPjQKJ2EAAADBAOOwQ2rdw8D/ElzM
nqDvkLKQdTeN6lQ6a3eb1/PyUrF0SLJzpzop2ZOyYSbf/2tAUzl91tvcO5NGOIsu/s7sCU
4aB/qJ61zf+/TRZDp1POq9f6kPcmQ+zJzLV9LjHOLn7Ur04RXHBsD4N0Ue/O4iQeZJX8Cq
i3G+yuuAMY0PD+Op1AVHrk+iOVsCFlkGBiK5bI+CE8Y3UjJIYejq9WQlhSwRMgSgckbW59
mUR492mBEobtjutwu75GyCqialFFTgQQAAAMEA2yq53+jQ5eVWsD2TiwhL2Iieyzpb0IdV
hBpAGPjE4Q+yYOsaYLX0hTS4ENi7E8diZJLPD6wNF9tT3Q9yzz7NBsuq86S15QF7gUZeuE
Ool2ooD4DvE1/6b37Vh8rMthCtOJ/HIPZMsNA5vuuyEhFcSpetLvyDzDLqmSe072QtD40S
JZXglXJTjziuSMOLbTEEBoBDMpANH5uHHNCVyvcAlzbZcgfdAeEIAgcDmObgSQ1inDqIo1
3nAdrXjKa6WX67AAAAFWFhcF8zMkBhbmRyZWktYWJyYW1vdwECAwQF

        passphrase: ${{ secrets.PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
        script: |
          # Выполняет pull образа c DockerHub
          sudo docker pull abramow79/8ec6f623a216f147ea97e04350cfaf67c9375a58aa087a43b09153afc164033f
          #остановка всех контейнеров
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 abramow79/8ec6f623a216f147ea97e04350cfaf67c9375a58aa087a43b09153afc164033f